### ISSUE TITLE
Configure Caproto server to cast PVs to network.

### ISSUE THREAD

**Issue by rajanplumley** [pcdshub/solid-attenuator#12]
Currently PVs can only be accessed by the localhost.  Going to need help with this one...

**Comment by rajanplumley** [comment]
From @klauer : 

> There are two options:
> (1) use the environment variables such as EPICS_CAS_INTF_ADDR_LIST (caproto respects these). see https://epics.anl.gov/base/R3-14/12-docs/CAref.html
> (2) use --interfaces (see python caproto/ioc_examples/io_interrupt.py --help) for the specific IOC instance

**Comment by klauer** [comment]
IOC running on ioc-lfe-srv01, accessed PVs from psbuild. I think this is probably OK.

Come to think of it, this may have been due to an older caproto version.
