### ISSUE TITLE
Implement SXR ladder style solid attenuator variant

### ISSUE THREAD

**Issue by rajanplumley** [pcdshub/solid-attenuator#16]
1. Generate ladder style filter configuration tables in `configurations.py`
2. Implement a `ladder-filter` style PVGroup 
3. Modify `IOCMain` to obtain transmissions and optimal filter combinations from ladder-style filters.
4. `:SET_CONFIG` PV will need to be flattened or altered to encode multiple states for each blade (as opposed to just 0 and 1)

**Comment by klauer** [comment]
Ladders can hold 8 filters, more than we originally thought: https://github.com/pcdshub/lcls-plc-sxr-satt/#filters

Will need to start prototyping this.
