### ISSUE TITLE
Possible filter material options should be obtained from HDF5 file

### ISSUE THREAD

**Issue by rajanplumley** [pcdshub/solid-attenuator#17]
https://github.com/pcdshub/hxr-attenuator/blob/dabdc3f68ebb032dda78351d8f71b7ef66c6d46f/caproto/ioc-satt-dev/db/filters.py#L17

**Comment by klauer** [comment]
Doing best-effort calculations with `periodictable` and code-level override for now. I think this is probably good to close.
