### ISSUE TITLE
`:T_CALC` should be renamed to not be confused with "current transmission"

### ISSUE THREAD

**Issue by rajanplumley** [pcdshub/solid-attenuator#18]
https://github.com/pcdshub/hxr-attenuator/blob/dabdc3f68ebb032dda78351d8f71b7ef66c6d46f/caproto/ioc-satt-dev/db/system.py#L10

This PV is the total transmission of all the filters together, which is useful for calculating the transmissions of the configurations matrix.  It is _not_ a readback of the transmission through the current filter configuration ( which requires awareness of the current filter position states ).

**Comment by klauer** [comment]
How does `T_CALC_ALL` sound? (i.e., **t**ransmission value **calc**ulated from **all** filters)

**Comment by klauer** [comment]
Resolved in a recent PR. Thanks!
